name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: war-file
          path: target/*.war

      # Add after 'Build with Maven' step
      - name: Trigger Jenkins Deployment
        uses: appleboy/jenkins-action@v1.4.0
        with:
            url: ${{ secrets.JENKINS_URL }}
            user: ${{ secrets.JENKINS_USER }}
            token: ${{ secrets.JENKINS_TOKEN }}
            job: TomcatDeployment
            parameters: "commit=${{ github.sha }}"
